#Одиночный
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.set_xlabel('Hue')
ax.set_ylabel('Saturation')
ax.set_zlabel('Value')
ax.scatter(ListForH,ListForS,ListForV)
plt.show()
#Цветной с разными точками
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.set_xlabel('Hue')
ax.set_ylabel('Saturation')
ax.set_zlabel('Value')
ax.scatter(ListForH,ListForS,ListForV)
ax.scatter(ListForCiclyHRed,ListForCiclySRed,ListForCiclyVRed)
ax.scatter(ListForCiclyHGreen,ListForCiclySGreen,ListForCiclyVGreen)
ax.scatter(ListForCiclyHYellow,ListForCiclySYellow,ListForCiclyVYellow)
plt.legend (("Количество точек больше 4","Количество точек = 1","Количество точек = 2", "Количетво точек = 3"))
plt.show()
